'use client';

import React from 'react';
import Hero from '@/components/Hero';
import Services from '@/components/Services';
import PropertyShowcase from '@/components/PropertyShowcase';
import About from '@/components/About';
import WhyChooseUs from '@/components/WhyChooseUs';
import Process from '@/components/Process';
import Contact from '@/components/Contact';
import Footer from '@/components/Footer';

export default function HomePage() {
  return (
    <>
      <main className="flex-1 container mx-auto px-4 py-8">
        {/* Components generated by the builder will be added here */}
      
        <Hero />
        <Services />
        <PropertyShowcase />
        <About />
        <WhyChooseUs />
        <Process />
        <Contact />
        <Footer />
      </main>
    </>
  );
}